# janus/core/auto_scanner.py
"""
Janus Auto Scanner - Comprehensive Security Assessment.

Automatically runs all relevant security tests against a target and
provides a unified report with findings from all modules.
"""

import time
from dataclasses import dataclass, field, asdict
from typing import Dict, List, Any, Optional, Callable
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor, as_completed
import json


@dataclass
class ScanModule:
    """A single scan module configuration."""
    name: str
    category: str
    description: str
    enabled: bool = True
    requires_param: bool = False


@dataclass
class ModuleResult:
    """Result from a single module scan."""
    module: str
    category: str
    status: str  # success, error, skipped
    vulnerable: bool
    severity: str  # CRITICAL, HIGH, MEDIUM, LOW, INFO
    findings_count: int
    findings: List[Dict]
    duration_ms: float
    error: Optional[str] = None
    
    def to_dict(self) -> Dict:
        return asdict(self)


@dataclass
class AutoScanReport:
    """Complete auto-scan report."""
    target_url: str
    scan_id: str
    scan_time: str
    duration_seconds: float
    total_modules: int
    completed_modules: int
    failed_modules: int
    total_findings: int
    critical_count: int
    high_count: int
    medium_count: int
    low_count: int
    results: List[ModuleResult] = field(default_factory=list)
    
    def to_dict(self) -> Dict:
        return {
            **{k: v for k, v in asdict(self).items() if k != 'results'},
            'results': [r.to_dict() for r in self.results]
        }
    
    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2)
    
    def to_html(self) -> str:
        """Generate HTML report."""
        severity_colors = {
            'CRITICAL': '#dc2626', 'HIGH': '#ea580c', 
            'MEDIUM': '#ca8a04', 'LOW': '#2563eb', 'INFO': '#6b7280'
        }
        
        findings_html = ""
        for r in self.results:
            if r.findings_count > 0:
                status_color = severity_colors.get(r.severity, '#6b7280')
                findings_html += f'''
                <div class="module-result" style="border-left: 4px solid {status_color}; padding: 15px; margin: 10px 0; background: #1e1e1e;">
                    <h3 style="margin: 0 0 10px 0;">{r.module} <span style="color: {status_color};">({r.severity})</span></h3>
                    <p style="color: #888;">Category: {r.category} | Findings: {r.findings_count}</p>
                    <ul style="margin: 10px 0;">
                        {"".join(f'<li style="color: #ccc;">{f.get("description", f.get("evidence", str(f)[:100]))}</li>' for f in r.findings[:5])}
                    </ul>
                </div>
                '''
        
        return f'''
<!DOCTYPE html>
<html>
<head>
    <title>Janus Security Report - {self.target_url}</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background: #121212; color: #fff; padding: 40px; }}
        .header {{ text-align: center; margin-bottom: 40px; }}
        .stats {{ display: flex; gap: 20px; justify-content: center; margin: 30px 0; }}
        .stat {{ background: #1e1e1e; padding: 20px 30px; border-radius: 10px; text-align: center; }}
        .stat-value {{ font-size: 2em; font-weight: bold; }}
        .critical {{ color: #dc2626; }}
        .high {{ color: #ea580c; }}
        .medium {{ color: #ca8a04; }}
        .low {{ color: #2563eb; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🔱 Janus Security Report</h1>
        <p style="color: #888;">Target: {self.target_url}</p>
        <p style="color: #666;">Scan ID: {self.scan_id} | Duration: {self.duration_seconds:.1f}s</p>
    </div>
    
    <div class="stats">
        <div class="stat">
            <div class="stat-value">{self.total_findings}</div>
            <div>Total Findings</div>
        </div>
        <div class="stat">
            <div class="stat-value critical">{self.critical_count}</div>
            <div>Critical</div>
        </div>
        <div class="stat">
            <div class="stat-value high">{self.high_count}</div>
            <div>High</div>
        </div>
        <div class="stat">
            <div class="stat-value medium">{self.medium_count}</div>
            <div>Medium</div>
        </div>
        <div class="stat">
            <div class="stat-value low">{self.low_count}</div>
            <div>Low</div>
        </div>
    </div>
    
    <h2>Findings by Module</h2>
    {findings_html if findings_html else '<p style="color: #666;">No vulnerabilities found.</p>'}
    
    <footer style="text-align: center; margin-top: 40px; color: #666;">
        Generated by Janus Security Scanner | {self.scan_time}
    </footer>
</body>
</html>
'''


class AutoScanner:
    """
    Automatic Security Scanner.
    
    Runs all available security modules against a target and
    generates a comprehensive report.
    """
    
    # Available scan modules
    MODULES = {
        'security_headers': ScanModule('Security Headers', 'Configuration', 'Check for missing/misconfigured security headers'),
        'cors': ScanModule('CORS', 'Configuration', 'Test for CORS misconfigurations'),
        'sensitive_files': ScanModule('Sensitive Files', 'Reconnaissance', 'Scan for exposed .git, .env, backups'),
        'fingerprint': ScanModule('Tech Fingerprint', 'Reconnaissance', 'Identify server technologies'),
        'open_redirect': ScanModule('Open Redirect', 'Injection', 'Test for unvalidated redirects'),
        'rate_limit': ScanModule('Rate Limiting', 'Configuration', 'Check if rate limiting is implemented'),
    }
    
    # Modules that need a parameter
    PARAM_MODULES = {
        'sqli': ScanModule('SQL Injection', 'Injection', 'Test for SQL injection', requires_param=True),
        'xss': ScanModule('XSS', 'Injection', 'Test for cross-site scripting', requires_param=True),
        'lfi': ScanModule('Path Traversal', 'Injection', 'Test for local file inclusion', requires_param=True),
    }
    
    def __init__(self, timeout: int = 30, threads: int = 5):
        self.timeout = timeout
        self.threads = threads
        self.progress_callback: Optional[Callable] = None
    
    def scan(
        self,
        url: str,
        token: Optional[str] = None,
        param: Optional[str] = None,
        modules: Optional[List[str]] = None
    ) -> AutoScanReport:
        """
        Run comprehensive security scan.
        
        Args:
            url: Target URL
            token: Optional authorization token
            param: Optional parameter for injection tests
            modules: Specific modules to run (all if None)
        
        Returns:
            AutoScanReport with all findings
        """
        start_time = time.time()
        scan_id = f"scan_{int(start_time)}"
        results: List[ModuleResult] = []
        
        # Determine which modules to run
        modules_to_run = {}
        for name, mod in self.MODULES.items():
            if modules is None or name in modules:
                modules_to_run[name] = mod
        
        # Add param-based modules if param provided
        if param:
            for name, mod in self.PARAM_MODULES.items():
                if modules is None or name in modules:
                    modules_to_run[name] = mod
        
        total = len(modules_to_run)
        completed = 0
        failed = 0
        
        # Run modules
        for name, mod in modules_to_run.items():
            try:
                if self.progress_callback:
                    self.progress_callback(name, completed, total)
                
                result = self._run_module(name, url, token, param)
                results.append(result)
                
                if result.status == 'error':
                    failed += 1
                completed += 1
                
            except Exception as e:
                results.append(ModuleResult(
                    module=mod.name,
                    category=mod.category,
                    status='error',
                    vulnerable=False,
                    severity='INFO',
                    findings_count=0,
                    findings=[],
                    duration_ms=0,
                    error=str(e)
                ))
                failed += 1
                completed += 1
        
        # Calculate totals
        duration = time.time() - start_time
        total_findings = sum(r.findings_count for r in results)
        critical = sum(1 for r in results if r.severity == 'CRITICAL' and r.vulnerable)
        high = sum(1 for r in results if r.severity == 'HIGH' and r.vulnerable)
        medium = sum(1 for r in results if r.severity == 'MEDIUM' and r.vulnerable)
        low = sum(1 for r in results if r.severity == 'LOW' and r.vulnerable)
        
        return AutoScanReport(
            target_url=url,
            scan_id=scan_id,
            scan_time=datetime.now().isoformat(),
            duration_seconds=duration,
            total_modules=total,
            completed_modules=completed,
            failed_modules=failed,
            total_findings=total_findings,
            critical_count=critical,
            high_count=high,
            medium_count=medium,
            low_count=low,
            results=results
        )
    
    def _run_module(
        self,
        module_name: str,
        url: str,
        token: Optional[str],
        param: Optional[str]
    ) -> ModuleResult:
        """Run a single scan module."""
        start = time.time()
        
        try:
            if module_name == 'security_headers':
                from janus.analysis.security_headers import SecurityHeadersScanner
                scanner = SecurityHeadersScanner(timeout=self.timeout)
                report = scanner.scan(url, token)
                
                # Count issues
                issues = [f for f in report.findings if f.status in ['MISSING', 'MISCONFIGURED']]
                severity = 'HIGH' if report.overall_grade in ['D', 'F'] else 'MEDIUM' if report.overall_grade == 'C' else 'LOW'
                
                return ModuleResult(
                    module='Security Headers',
                    category='Configuration',
                    status='success',
                    vulnerable=len(issues) > 0,
                    severity=severity,
                    findings_count=len(issues),
                    findings=[{'header': f.header_name, 'status': f.status, 'description': f.recommendation} for f in issues],
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'cors':
                from janus.analysis.cors_scanner import CORSScanner
                scanner = CORSScanner(timeout=self.timeout)
                report = scanner.scan(url, token)
                
                severity = 'CRITICAL' if report.critical_findings > 0 else 'HIGH' if report.high_findings > 0 else 'MEDIUM'
                
                return ModuleResult(
                    module='CORS',
                    category='Configuration',
                    status='success',
                    vulnerable=report.vulnerable,
                    severity=severity,
                    findings_count=len(report.findings),
                    findings=[f.to_dict() for f in report.findings],
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'sensitive_files':
                from janus.recon.sensitive_files import SensitiveFileScanner
                scanner = SensitiveFileScanner(timeout=self.timeout)
                report = scanner.scan(url, token)
                
                # Only count HIGH confidence findings
                verified_findings = [f for f in report.findings if f.confidence == 'HIGH']
                severity = 'CRITICAL' if report.critical_findings > 0 else 'HIGH' if report.high_findings > 0 else 'MEDIUM'
                
                return ModuleResult(
                    module='Sensitive Files',
                    category='Reconnaissance',
                    status='success',
                    vulnerable=len(verified_findings) > 0,
                    severity=severity if verified_findings else 'INFO',
                    findings_count=len(verified_findings),
                    findings=[f.to_dict() for f in verified_findings],
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'fingerprint':
                from janus.recon.tech_fingerprint import TechFingerprinter
                fp = TechFingerprinter(timeout=self.timeout)
                report = fp.fingerprint(url, token)
                
                return ModuleResult(
                    module='Tech Fingerprint',
                    category='Reconnaissance',
                    status='success',
                    vulnerable=False,  # Info only
                    severity='INFO',
                    findings_count=len(report.technologies),
                    findings=[t.to_dict() for t in report.technologies],
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'open_redirect':
                from janus.attack.open_redirect import OpenRedirectScanner
                scanner = OpenRedirectScanner(timeout=self.timeout)
                result = scanner.quick_scan(url, token)
                
                return ModuleResult(
                    module='Open Redirect',
                    category='Injection',
                    status='success',
                    vulnerable=result.get('vulnerable', False),
                    severity='MEDIUM',
                    findings_count=result.get('vulnerable_params', 0),
                    findings=result.get('findings', []),
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'rate_limit':
                from janus.attack.rate_limit_tester import RateLimitTester
                tester = RateLimitTester(timeout=self.timeout)
                result = tester.test_endpoint(url, "GET", token, num_requests=20)
                
                return ModuleResult(
                    module='Rate Limiting',
                    category='Configuration',
                    status='success',
                    vulnerable=not result.rate_limit_detected,
                    severity='HIGH' if not result.rate_limit_detected else 'INFO',
                    findings_count=1 if not result.rate_limit_detected else 0,
                    findings=[{'evidence': result.evidence, 'recommendation': result.recommendation}] if not result.rate_limit_detected else [],
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'sqli' and param:
                from janus.attack.sqli_detector import SQLiDetector
                detector = SQLiDetector(timeout=self.timeout)
                report = detector.scan(url, [param], token)
                
                return ModuleResult(
                    module='SQL Injection',
                    category='Injection',
                    status='success',
                    vulnerable=report.vulnerable_params > 0,
                    severity='CRITICAL',
                    findings_count=len([f for f in report.findings if f.vulnerable]),
                    findings=[f.to_dict() for f in report.findings if f.vulnerable],
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'xss' and param:
                from janus.attack.xss_scanner import XSSScanner
                scanner = XSSScanner(timeout=self.timeout)
                report = scanner.scan(url, [param], token)
                
                return ModuleResult(
                    module='XSS',
                    category='Injection',
                    status='success',
                    vulnerable=report.vulnerable_params > 0,
                    severity='HIGH',
                    findings_count=len([f for f in report.findings if f.vulnerable]),
                    findings=[f.to_dict() for f in report.findings if f.vulnerable],
                    duration_ms=(time.time() - start) * 1000
                )
            
            elif module_name == 'lfi' and param:
                from janus.attack.path_traversal import PathTraversalScanner
                scanner = PathTraversalScanner(timeout=self.timeout)
                report = scanner.scan(url, [param], token)
                
                return ModuleResult(
                    module='Path Traversal',
                    category='Injection',
                    status='success',
                    vulnerable=report.vulnerable_params > 0,
                    severity='CRITICAL',
                    findings_count=len([f for f in report.findings if f.vulnerable]),
                    findings=[f.to_dict() for f in report.findings if f.vulnerable],
                    duration_ms=(time.time() - start) * 1000
                )
            
            else:
                return ModuleResult(
                    module=module_name,
                    category='Unknown',
                    status='skipped',
                    vulnerable=False,
                    severity='INFO',
                    findings_count=0,
                    findings=[],
                    duration_ms=(time.time() - start) * 1000
                )
                
        except Exception as e:
            return ModuleResult(
                module=module_name,
                category='Unknown',
                status='error',
                vulnerable=False,
                severity='INFO',
                findings_count=0,
                findings=[],
                duration_ms=(time.time() - start) * 1000,
                error=str(e)
            )
    
    def get_available_modules(self) -> Dict[str, Dict]:
        """Get list of available scan modules."""
        modules = {}
        for name, mod in self.MODULES.items():
            modules[name] = {
                'name': mod.name,
                'category': mod.category,
                'description': mod.description,
                'requires_param': mod.requires_param
            }
        for name, mod in self.PARAM_MODULES.items():
            modules[name] = {
                'name': mod.name,
                'category': mod.category,
                'description': mod.description,
                'requires_param': mod.requires_param
            }
        return modules
